"""
Optimized Pathfinding with Risk Awareness

Demonstrates how to use risk metrics to plan safer drone routes.
Generates altitude profiles for waypoints using different strategies.
"""

import csv
from kimDroneGoon.geo import geodata
from kimDroneGoon.drone import Drone
from kimDroneGoon.simulation import DroneSimulator
from kimDroneGoon.visualize import visualizer
from risk_aware_routing import RiskAwareRouter, compare_routing_strategies


def load_altitude_stats(csv_file='altitude_summary.csv'):
    """
    Loads altitude statistics from the CSV generated by altitude_analysis.py
    """
    alt_stats = {}
    
    try:
        with open(csv_file, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                altitude_ft = int(row['altitude_ft'])
                alt_stats[altitude_ft] = {
                    'avg_velocity_mps': float(row['avg_velocity_mps']),
                    'avg_kinetic_energy_j': float(row['avg_kinetic_energy_j']),
                    'avg_death_probability': float(row['avg_death_probability']),
                    'casualty_probability': float(row['casualty_probability'])
                }
        print(f"[*] Loaded altitude statistics for {len(alt_stats)} altitudes")
        return alt_stats
    
    except FileNotFoundError:
        print(f"[!] Could not find {csv_file}")
        print("    Run altitude_analysis.py first to generate this file")
        return None


def main():
    print("="*70)
    print("OPTIMIZED PATHFINDING WITH RISK AWARENESS")
    print("="*70)
    
    # Load altitude stats from previous analysis
    print("\n[*] Loading altitude analysis results...")
    alt_stats = load_altitude_stats('altitude_summary.csv')
    
    if alt_stats is None:
        print("[!] Cannot proceed without altitude statistics")
        return
    
    # Initialize data
    print("[*] Initializing geospatial data...")
    data = geodata(
        "kimDroneGoon/datasets/worldpopHK/hkg_ppp_2020_UNadj_constrained.tif",
        "kimDroneGoon/datasets/LUMHK_RasterGrid_2024/BLU.tif",
        "kimDroneGoon/datasets/sandboxZones/map.geojson"
    )
    
    # Create drone
    drone = Drone(
        name="DJI Matrice 300 RTK",
        emptyWeightKg=6.3,
        maxPayloadKg=2.7,
        maxRangeKm=15.0,
        maxSpeedKmh=82.8
    )
    
    # Initialize simulator
    simulator = DroneSimulator(drone, data)
    
    # Get optimized drone path
    print("[*] Computing optimized drone path...")
    v = visualizer(data)
    route_gdf = v.getOptimizedDronePath()
    
    if route_gdf is None or len(route_gdf) < 3:
        print("[!] Could not compute drone path")
        return
    
    print(f"[*] Route has {len(route_gdf)} waypoints")
    
    # Initialize risk-aware router
    router = RiskAwareRouter(simulator, alt_stats)
    
    # Compare routing strategies
    print("\n[*] Evaluating routing strategies...")
    results = compare_routing_strategies(simulator, alt_stats, route_gdf)
    
    # Generate detailed profiles for each strategy
    print("\n[*] Generating altitude profiles...")
    
    strategies = ['low', 'high', 'mixed', 'optimal']
    profiles = {}
    
    output_file = open('altitude_profiles.csv', 'w', newline='')
    writer = csv.DictWriter(output_file, fieldnames=[
        'waypoint_id', 'latitude', 'longitude', 'population',
        'low_alt', 'high_alt', 'mixed_alt', 'optimal_alt',
        'low_risk', 'high_risk', 'mixed_risk', 'optimal_risk'
    ])
    writer.writeheader()
    
    for strategy in strategies:
        profiles[strategy] = router.generate_altitude_profile(route_gdf, strategy)
    
    # Write detailed waypoint profiles
    for wp_idx, (_, row) in enumerate(route_gdf.iterrows()):
        pop = row.get('pop', 0)
        lat = row.geometry.y
        lng = row.geometry.x
        
        # Compute risk for each altitude
        altitude_risks = {}
        for strategy in strategies:
            altitude_ft = profiles[strategy][wp_idx]
            casualty_prob = router.compute_casualty_probability(pop, altitude_ft)
            altitude_risks[f'{strategy}_alt'] = altitude_ft
            altitude_risks[f'{strategy}_risk'] = casualty_prob
        
        writer.writerow({
            'waypoint_id': wp_idx,
            'latitude': lat,
            'longitude': lng,
            'population': pop,
            'low_alt': profiles['low'][wp_idx],
            'high_alt': profiles['high'][wp_idx],
            'mixed_alt': profiles['mixed'][wp_idx],
            'optimal_alt': profiles['optimal'][wp_idx],
            'low_risk': router.compute_casualty_probability(pop, profiles['low'][wp_idx]),
            'high_risk': router.compute_casualty_probability(pop, profiles['high'][wp_idx]),
            'mixed_risk': router.compute_casualty_probability(pop, profiles['mixed'][wp_idx]),
            'optimal_risk': router.compute_casualty_probability(pop, profiles['optimal'][wp_idx])
        })
    
    output_file.close()
    print(f"    └─ Wrote waypoint profiles to altitude_profiles.csv")
    
    # Recommendations
    print("\n" + "="*70)
    print("RECOMMENDATIONS")
    print("="*70)
    
    best_strategy = min(results.keys(), 
                       key=lambda s: results[s]['total_casualty_probability'])
    
    print(f"\n✓ BEST STRATEGY: '{best_strategy}'")
    print(f"  Total Risk: {results[best_strategy]['total_casualty_probability']:.4f}")
    print(f"  Avg Risk per WP: {results[best_strategy]['avg_casualty_probability']:.6f}")
    print(f"  High-Risk Waypoints: {len(results[best_strategy]['high_risk_waypoints'])}")
    
    print(f"\nKey Insights:")
    print(f"  - 'low' strategy: Safest for impact energy (but may take longer)")
    print(f"  - 'high' strategy: Faster operations (but higher casualty risk)")
    print(f"  - 'mixed' strategy: Balance between speed and safety")
    print(f"  - 'optimal' strategy: Customized per waypoint population")
    
    print(f"\n→ Recommended approach:")
    print(f"  Use '{best_strategy}' strategy with the generated altitude profile")
    print(f"  in altitude_profiles.csv")
    
    print("="*70 + "\n")


if __name__ == '__main__':
    main()
